const RX_APP_GLOBAL = {
    RX_APP_GLOBAL_CLEAR: 'RX_APP_GLOBAL_CLEAR',
    RX_APP_GLOBAL_SET_LOADING_ON: 'RX_APP_GLOBAL_SET_LOADING_ON',
    RX_APP_GLOBAL_SET_LOADING_OFF: 'RX_APP_GLOBAL_SET_LOADING_OFF',
};

const RX_APP_TASK = {
    RX_APP_TASK_CLEAR: 'RX_APP_TASK_CLEAR',
    RX_APP_TASK_SET_LIST: 'RX_APP_TASK_SET_LIST',
    RX_APP_TASK_ITEM_ADD: 'RX_APP_TASK_ITEM_ADD',
    RX_APP_TASK_ITEM_DEL: 'RX_APP_TASK_ITEM_DEL',
    RX_APP_TASK_ITEM_UPD: 'RX_APP_TASK_ITEM_UPD',
};

const RX_APP_FILTER = {
    RX_APP_FILTER_CLEAR: 'RX_APP_FILTER_CLEAR',
    RX_APP_FILTER_SET_PENDING: 'RX_APP_FILTER_SET_PENDING',
    RX_APP_FILTER_SET_OPEN: 'RX_APP_FILTER_SET_OPEN',
    RX_APP_FILTER_SET_ALL: 'RX_APP_FILTER_SET_ALL',
};

export {
    RX_APP_GLOBAL,
    RX_APP_TASK,
    RX_APP_FILTER,
};
